service: gpuci-serverless-ops-bot-probot

provider:
  name: aws
  region: us-east-2
  timeout: 900 # mv to function once consolidated
  memorySize: 1024
  stage: dev
  runtime: nodejs18.x
  logRetentionInDays: 60
  apiGateway:
    shouldStartNameWithService: true
  deploymentBucket:
    name: rapids-serverless-deployments
  environment:
    NODE_ENV: production
    LOG_FORMAT: json
    LOG_LEVEL: debug
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "lambda:InvokeFunction"
          Resource:
            Fn::Sub:
              - arn:aws:lambda:${aws:region}:${aws:accountId}:function:${AWS::StackName}-${fnName}
              # A YAML anchor is used since `Ref` results in circular dependency issues between
              # the Lambda function and this policy.
              - fnName: &probotFn handleProbot

functions:
  *probotFn :
    handler: dist/probot.handler
    events:
      - http:
          path: /probot
          method: GET
    environment:
      APP_ID: ${env:APP_ID}
      WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
      PRIVATE_KEY: ${env:PRIVATE_KEY}
  authorizerFn:
    handler: dist/authorizer.handler
    environment:
      probotFnName:
        Fn::Sub:
          - ${AWS::StackName}-${fnName}
          - fnName: *probotFn
      PRIVATE_KEY: ${env:PRIVATE_KEY}
    events:
      - http:
          path: /
          method: POST
