service: gpuci-serverless-ops-bot-probot

provider:
  name: aws
  region: us-east-2
  timeout: 300
  memorySize: 1024
  stage: dev
  runtime: nodejs14.x
  logRetentionInDays: 60
  apiGateway:
    shouldStartNameWithService: true
  deploymentBucket:
    name: rapids-serverless-deployments

functions:
  handleProbot:
    handler: dist/serverless.probot
    events:
      - http:
          path: /
          method: POST
          async: true
      - http:
          path: /probot
          method: GET
    environment:
      LOG_LEVEL: debug
      APP_ID: ${env:APP_ID}
      WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
      PRIVATE_KEY: ${env:PRIVATE_KEY}
  nvidiaOrgProbot:
    handler: dist/serverless.probot
    events:
      - http:
          path: /nvidia-org
          method: POST
          async: true
    environment:
      LOG_LEVEL: debug
      APP_ID: ${env:NVIDIA_ORG_APP_ID}
      WEBHOOK_SECRET: ${env:NVIDIA_ORG_WEBHOOK_SECRET}
      PRIVATE_KEY: ${env:NVIDIA_ORG_PRIVATE_KEY}
